swagger: '2.0'
info:
  title: Sample API
  description: Sample api representing an user resource
  version: "1.0.0"
host: localhost:8000
basePath: /v1
produces:
  - application/json
consumes:
  - application/json
paths:
  /users/:
    get:
      summary: Returns a list of users
      responses:
        200:
          description: Success
          schema:
            type: array
            items:
              $ref: '#/definitions/User'
    post:
      summary: Create a new user
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/User'
      responses:
        201:
          description: Created
          schema:
            $ref: '#/definitions/User'
        400:
          description: Input error
  /users/{id}:
    get:
      summary: Returns a specific user
      parameters:
        - name: id
          in: path
          required: true
          type: integer
      responses:
        200:
          description: Success
          schema:
            $ref: '#/definitions/User'
        404:
          description: User not found
    put:
      summary: Update an user
      parameters:
        - name: id
          in: path
          required: true
          type: integer
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/User'
      responses:
        200:
          description: Success
          schema:
            $ref: '#/definitions/User'
        400:
          description: Input error
        404:
          description: User not found
    delete:
      summary: Delete an user
      parameters:
        - name: id
          in: path
          required: true
          type: integer
      responses:
        204:
          description: Success
        404:
          description: User not found
definitions:
  User:
    type: object
    required:
      - name
      - email
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
        description: Must be unique
      email:
        type: string
        format: email
        example: me@example.com
      dateJoined:
        type: string
        format: date
      permissions:
        type: array
        items:
          type: string
          enum:
            - READ
            - WRITE
            - CREATE
            - DELETE
        example: ['READ', 'CREATE']
